atem:
  host: 192.168.1.69
  debug: false

control:
  port: 8090

mqtt:
  broker:
  #  host: 192.168.1.30
    port: 1883
  topics:
    tally:
      state: "tally/{0}/state"

  clientOptions:
    # If connection is lost, try reconnecting after X ms
    # (0 disables automatic reconnection completely!)
    reconnectPeriod: 500
    connectTimeout: 5000
