atem:
  use_mdns: true
  mdns_name: ATEM Mini Extreme ISO._blackmagic._tcp.local
  debug: false
  host: ""
control:
  httpPort: 8090
  websocketPort: 8091
mqtt:
  broker:
    port: 1883
  topics:
    tally:
      state: tally/{0}/state
  clientOptions:
    reconnectPeriod: 500
    connectTimeout: 5000
x32:
  host: 192.168.23.202
  tally_mapping:
    "1": 15
    "2": 16
