atem:
  use_mdns: true
  #use_mdns: false
  mdns_name: "ATEM Mini Extreme ISO._blackmagic._tcp.local"
  #host: 192.168.0.120
  #host: 192.168.1.69
  debug: false


# Control web server configuration
control:
  httpPort: 8090
  websocketPort: 8091


mqtt:
  broker:
  #  host: 192.168.1.30
    port: 1883
  topics:
    tally:
      state: "tally/{0}/state"

  clientOptions:
    # If connection is lost, try reconnecting after X ms
    # (0 disables automatic reconnection completely!)
    reconnectPeriod: 500
    connectTimeout: 5000


# For receiving (un)mute events for talkback channels from the Tally devices
x32:
  host: 192.168.23.202

  # Which tally number (left) triggers which channel's (right) mute state
  tally_mapping:
    1: 15
    2: 16
