---

name: Package and Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: ./node_modules/.bin/pkg .
      - run: |
          cd native-ui && \
          sudo apt-get -y install wine64 && \
          yarn install --frozen-lockfile && \
          cp ../config.yml ./config.yml && \
          cp ../dist/tally-server-linux ./tally-server && yarn make --platform linux && \
          cp ../dist/tally-server-macos ./tally-server && yarn make --platform darwin && \
          cp ../dist/tally-server-win.exe ./tally-server && yarn make --platform win32

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/tally-server-linux
            ./dist/tally-server-win.exe
            ./dist/tally-server-macos
            ./native-ui/out/make/zip/linux/x64/*.zip
            ./native-ui/out/make/zip/win32/x64/*.zip
            ./native-ui/out/make/zip/darwin/x64/*.zip
