---

name: Package and Release

on:
  create:
    tags:
      - v*

jobs:
  build-cli:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd cli && \
          yarn install --frozen-lockfile && \
          yarn make
      - uses: actions/upload-artifact@v3
        with:
          name: cli-linux
          path: ./cli/dist/tally-server-*

  build-ui-linux-win:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: sudo apt-get -y install wine64
      - run: |
          cd native-ui && \
          yarn install --frozen-lockfile && \
          yarn make-linux && \
          yarn make-win32
      - uses: actions/upload-artifact@v3
        with:
          name: ui-linux-win
          path: ./native-ui/out/make/**

  build-ui-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd native-ui && \
          yarn install --frozen-lockfile && \
          yarn make-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: ui-macos
          path: ./native-ui/out/make/**

  release:
    needs:
      - build-cli
      - build-ui-linux-win
      - build-ui-macos
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**
